version: "3"

services:
  cadvisor:
    restart: always
    image: gcr.io/google-containers/cadvisor@sha256:16bc6858dc5b7063c7d89153ad6544370eb79cb27a1b8d571f31b98673f7a324
    container_name: cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/snap/docker/current:/var/lib/docker:ro"
    expose:
      - "8080"
    ports:
      - 8085:8080

  prometheus:
    restart: always
    depends_on:
      - digitalocean-exporter
    image: prom/prometheus@sha256:f4a858861e05c8611cdb5867a07e48742b8295400a5993ac05ad1ee67e6d5696
    container_name: prometheus
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PWD}/rules.yml:/etc/alertmanager/rules.yml
    expose:
      - "9090"
    ports:
      - 9090:9090

  alertmanager:
    restart: always
    depends_on:
      - prometheus
    image: prom/alertmanager@sha256:913293083cb14085bfc01018bb30d1dcbbc9ed197ae21ef2ca917b0d29265198
    container_name: alertmanager
    volumes:
      - ${PWD}/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    expose:
      - "9093"
    ports:
      - 9093:9093

  digitalocean-exporter:
    image: ghcr.io/dazwilkin/digitalocean_exporter:17c7d9812dd9dc878c70d5a2335c966b3cac681b
    container_name: digitalocean-exporter
    environment:
      - DIGITALOCEAN_TOKEN
    expose:
      - "9212"
    ports:
      - 9212:9212
